name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        uses: webfactory/ssh-agent@v0.4.1

      - name: Add SSH key
        run: ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

      - name: Copy JAR file
        run: scp target/FileConverter.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/FileConverter.jar

      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          distribution: container
          script: |
            cd /path/to/app
            sudo systemctl restart FileConverter.service
